// Taxonomia de Setor → Sub-setor usada nas empresas (clients).
// Os valores aqui refletem a base atual de 712 empresas.

export const SECTORS_MAP: Record<string, string[]> = {
  "Advocacia e Serviços Jurídicos": ["Escritório de Advocacia", "Legaltech"],
  "Agronegócio": [
    "Agronegócio (Geral)",
    "Cooperativa Agrícola",
    "Floricultura",
    "Insumos Agrícolas",
    "Paisagismo",
    "Pecuária",
    "Pesquisa Agrícola",
    "Processamento de Grãos",
    "Sementes",
    "Trading Agrícola",
  ],
  "Alimentos e Bebidas": [
    "Alimentos Saudáveis",
    "Bebidas",
    "Café",
    "Confeitaria",
    "Franquias de Alimentação",
    "Indústria de Alimentos",
    "Laticínios",
    "Restaurantes e Food Service",
    "Sorvetes",
  ],
  "Construção Civil e Engenharia": [
    "Arquitetura",
    "Construção Civil",
    "Construção Naval",
    "Engenharia Ambiental",
    "Engenharia de Energia",
    "Engenharia de Segurança",
    "Infraestrutura e Concessões",
    "Projetos de Engenharia",
    "Saneamento",
  ],
  "Consultoria e Auditoria": [
    "Assessoria Financeira",
    "Auditoria",
    "Consultoria (Geral)",
    "Consultoria de Gestão",
    "Consultoria Tributária",
    "Contabilidade",
    "Reestruturação Corporativa",
  ],
  "Educação": [
    "EdTech",
    "Educação (Geral)",
    "Ensino Básico",
    "Ensino Superior",
    "Idiomas",
    "Treinamento Profissional",
  ],
  "Energia": [
    "Comercialização de Energia",
    "Energia (Geral)",
    "Energia Solar",
    "Geração de Energia",
    "Transmissão de Energia",
    "Utilidade Pública",
  ],
  "Entretenimento e Eventos": [
    "Brinquedos e Jogos",
    "Eventos e Shows",
    "Jogos Eletrônicos",
    "Live Marketing",
    "Produção Audiovisual",
    "Streaming",
  ],
  "Esporte e Futebol": ["Academias e Fitness", "Equipe de Futebol", "Esporte e Lazer"],
  "Holding / Participações": ["Holding de Participações"],
  "Hotelaria e Turismo": ["Hotelaria e Turismo", "Marinas"],
  "Incorporação e Mercado Imobiliário": [
    "Administração Imobiliária",
    "Incorporação Imobiliária",
    "Loteamento e Desenvolvimento Urbano",
    "Shopping Centers",
  ],
  "Indústria / Manufatura": [
    "Autopeças e Automotivo",
    "Componentes Industriais",
    "Defesa e Segurança",
    "Eletrônicos",
    "Etiquetas e Adesivos",
    "Indústria de Embalagens",
    "Indústria Têxtil",
    "Máquinas e Equipamentos",
    "Materiais de Construção",
    "Papel e Celulose",
    "Refrigeração e Climatização",
  ],
  "Logística e Transportes": [
    "Armazenagem",
    "Locação de Veículos",
    "Logística e Distribuição",
    "Mudanças",
    "Transporte Aéreo",
    "Transporte de Gás",
    "Transporte de Passageiros",
    "Transporte Ferroviário",
    "Transporte Rodoviário de Carga",
  ],
  "Mídia, Publicidade e Marketing": [
    "Design",
    "Editoração",
    "Mídia",
    "Publicidade Digital",
    "Publicidade e Marketing",
    "Relações Públicas",
  ],
  "Mineração e Metalurgia": [
    "Alumínio",
    "Metalurgia",
    "Mineração",
    "Mineração de Calcário",
    "Mineração de Ferro",
    "Mineração de Fertilizantes",
    "Mineração de Ouro",
    "Siderurgia",
  ],
  "Óleo e Gás": ["Exploração de Petróleo e Gás", "Serviços Offshore"],
  "Outros / Descartado": [
    "Empresa Estrangeira",
    "Não Identificado",
    "Registro Descartado",
    "Sem Proposta",
  ],
  "Pessoa Física": ["Pessoa Física"],
  "Private Equity / Gestão de Recursos": [
    "Asset Management",
    "Gestão de Recursos",
    "Private Equity",
    "Venture Capital",
  ],
  "Química e Farmacêutica": [
    "Asfaltos",
    "Cosméticos",
    "Indústria Farmacêutica",
    "Indústria Química",
    "Resinas",
  ],
  "Recursos Humanos e Facilities": [
    "Facilities e Terceirização",
    "Leilões Corporativos",
    "Recursos Humanos",
  ],
  "Saúde": [
    "Clínicas Especializadas",
    "Equipamentos Médicos",
    "Hospitalar",
    "Medicina Diagnóstica",
    "Pesquisa em Saúde",
    "Planos de Saúde",
    "Saúde Animal",
    "Saúde Digital",
    "Saúde Mental",
    "Serviços Médicos",
  ],
  "Seguros": [
    "Corretora de Seguros",
    "Insurtech",
    "Planos de Saúde",
    "Resseguros",
    "Seguros (Geral)",
  ],
  "Serviços Financeiros": [
    "Banco",
    "Consórcios",
    "Corretora de Valores",
    "Crédito e Cobrança",
    "Fintech",
    "Meios de Pagamento",
    "Securitização",
    "Serviços Financeiros (Geral)",
  ],
  "Setor Público": [
    "Administração Condominial",
    "Administração Pública",
    "Apoio a Pequenas Empresas",
    "Conselho de Classe",
    "Defesa Pública",
    "Governo Digital",
    "Infraestrutura Pública",
    "Telecom Público",
    "Trânsito e Urbanização",
  ],
  "Tecnologia / TI": [
    "Certificação Digital",
    "Cibersegurança",
    "Consultoria de TI",
    "E-commerce / Tech",
    "IA e Dados",
    "Informações e Analytics",
    "IoT e Rastreabilidade",
    "Plataformas Digitais",
    "Software / SaaS",
    "Tecnologia (Geral)",
  ],
  "Telecomunicações": ["Provedor de Internet", "Telecomunicações"],
  "Terceiro Setor / Associações": [
    "Associação / ONG",
    "Filantropia",
    "Serviços Assistenciais",
  ],
  "Varejo e Comércio": [
    "Bens de Consumo",
    "Concessionárias de Veículos",
    "Distribuição",
    "Eletrônicos e Eletrodomésticos",
    "Moda e Vestuário",
    "Pet Shop",
    "Supermercados e Atacado",
    "Varejo (Geral)",
    "Varejo Farmacêutico",
  ],
};

export const SECTORS = Object.keys(SECTORS_MAP).sort((a, b) =>
  a.localeCompare(b, "pt-BR"),
);

export const UFS: { sigla: string; nome: string }[] = [
  { sigla: "AC", nome: "Acre" },
  { sigla: "AL", nome: "Alagoas" },
  { sigla: "AP", nome: "Amapá" },
  { sigla: "AM", nome: "Amazonas" },
  { sigla: "BA", nome: "Bahia" },
  { sigla: "CE", nome: "Ceará" },
  { sigla: "DF", nome: "Distrito Federal" },
  { sigla: "ES", nome: "Espírito Santo" },
  { sigla: "GO", nome: "Goiás" },
  { sigla: "MA", nome: "Maranhão" },
  { sigla: "MT", nome: "Mato Grosso" },
  { sigla: "MS", nome: "Mato Grosso do Sul" },
  { sigla: "MG", nome: "Minas Gerais" },
  { sigla: "PA", nome: "Pará" },
  { sigla: "PB", nome: "Paraíba" },
  { sigla: "PR", nome: "Paraná" },
  { sigla: "PE", nome: "Pernambuco" },
  { sigla: "PI", nome: "Piauí" },
  { sigla: "RJ", nome: "Rio de Janeiro" },
  { sigla: "RN", nome: "Rio Grande do Norte" },
  { sigla: "RS", nome: "Rio Grande do Sul" },
  { sigla: "RO", nome: "Rondônia" },
  { sigla: "RR", nome: "Roraima" },
  { sigla: "SC", nome: "Santa Catarina" },
  { sigla: "SP", nome: "São Paulo" },
  { sigla: "SE", nome: "Sergipe" },
  { sigla: "TO", nome: "Tocantins" },
];

export const UF_SIGLAS = UFS.map((u) => u.sigla);

export function isForeignUf(value?: string | null): boolean {
  if (!value) return false;
  return !UF_SIGLAS.includes(value.toUpperCase());
}
